export interface SampleReview {
  id: string;
  kategoriSlug: string;       // "otomobil" | "arazi-suv" | "motosiklet" | "ticari"
  marka: string;              // vehicles-data.ts'deki marka adıyla eşleşmeli
  model: string;              // vehicles-data.ts'deki model adıyla eşleşmeli
  kasaKod: string;            // vehicles-data.ts'deki kasa.kod ile eşleşmeli
  yil: number;
  kullanici: string;
  puan: number;               // 1-5
  baslik: string;
  icerik: string;             // 3-5 cümle, samimi Türkçe
  olumlu: string[];           // 2-4 madde
  olumsuz: string[];          // 2-4 madde
  sentimentType: "COMPLAINT" | "POSITIVE" | "TIP";
  tarih: string;              // "YYYY-MM-DD"
}

export const sampleReviews: SampleReview[] = [
  // ─── OTOMOBİL (15 adet) ───────────────────────────────────────────────────

  {
    id: "rev-001",
    kategoriSlug: "otomobil",
    marka: "Volkswagen",
    model: "Golf",
    kasaKod: "Mk7",
    yil: 2016,
    kullanici: "andmcetin",
    puan: 4,
    baslik: "Golf 7 ile 3 Yıl: Sürüş Keyfi vs Servis Maliyeti",
    icerik: "Golf 7'yi 2016 model aldım, şu an 95 bin km'de. DSG'nin şehir trafiğindeki konforu tartışmasız ama 60 bin km'de kavrama değişimi 18 bin TL'ye patladı. Kış lastikleriyle bile yol tutuşu harika, sadece servis faturalarına hazırlıklı olun.",
    olumlu: ["DSG şanzıman konforu", "Üstün yol tutuşu", "Kabin ses yalıtımı", "Yakıt tüketimi (şehir dışı 5.8L/100km)"],
    olumsuz: ["DSG erken kavrama aşınması", "Yüksek servis maliyeti", "Şehir içi yakıt (8.5L/100km)"],
    sentimentType: "TIP",
    tarih: "2024-08-12",
  },

  {
    id: "rev-002",
    kategoriSlug: "otomobil",
    marka: "Renault",
    model: "Clio",
    kasaKod: "Mk5",
    yil: 2021,
    kullanici: "mervekaradag",
    puan: 5,
    baslik: "Clio 5 ile İstanbul Trafiğinde İki Yıl",
    icerik: "1.0 TCe ile beklediğimden çok daha az yakıyor, şehir içinde 7 litreye düşürmeyi başardım. Gösterge tasarımı ilk haftalar şaşırtıcı ama alışınca keyifli. Dar park yerlerinde yüksek ön köşe görüşüyle çok kolay manevra yapılıyor.",
    olumlu: ["Düşük yakıt tüketimi", "Modern iç tasarım", "Küçük ölçüde kolay park", "Düşük sigorta maliyeti"],
    olumsuz: ["Arka yolcu baş mesafesi kısıtlı", "Orta konsol küçük", "1.0 TCe üst hızda sesli"],
    sentimentType: "POSITIVE",
    tarih: "2023-11-05",
  },

  {
    id: "rev-003",
    kategoriSlug: "otomobil",
    marka: "Fiat",
    model: "Egea",
    kasaKod: "356",
    yil: 2019,
    kullanici: "hakankurt81",
    puan: 2,
    baslik: "Egea Sedan: Servis Ağı İyi Ama Pas Sorunu Kabul Edilemez",
    icerik: "36 bin km'de arka çamurluklar paslanmaya başladı, bu tamamen üretim hatası. Garantiden kabul etmeyeceklerini söylediklerinde şok oldum. Şehir içi kullanım için alanı geniş ve yakıt ekonomisi iyi ama kaporta kalitesi bu fiyatta ciddi eksiklik.",
    olumlu: ["Geniş bagaj hacmi (520L)", "Uygun servis ağı", "Şehir içi yakıt ekonomisi"],
    olumsuz: ["Arka çamurluk pas sorunu", "Garanti konusunda direniş", "Plastik iç malzeme kalitesi düşük", "Yol sesi kabin içine geçiyor"],
    sentimentType: "COMPLAINT",
    tarih: "2024-02-18",
  },

  {
    id: "rev-004",
    kategoriSlug: "otomobil",
    marka: "Toyota",
    model: "Corolla",
    kasaKod: "E210",
    yil: 2020,
    kullanici: "serapyilmaz",
    puan: 5,
    baslik: "Hybrid Teknolojisi Türkiye Şehir Trafiğinde Gerçekten Fark Yaratıyor",
    icerik: "İstanbul trafiğinde 4.2L/100km gibi bir ortalama yakaladım, bu sonucu başka hiçbir araçta görmedim. Aküyü kendisi şarj ettiği için dışarıdan bağlantı gerektirmiyor, uzun vadede akü değişim maliyeti endişesi yaratsa da Toyota'nın 10 yıl akü garantisi güven veriyor. 85 bin km'de hiçbir arıza yaşamadım.",
    olumlu: ["İstisna yakıt ekonomisi (hibrit)", "Güvenilir Toyota kalitesi", "10 yıl akü garantisi", "Düşük CO2 vergisi avantajı"],
    olumsuz: ["Hibrit sistemi nedeniyle yüksek ilk maliyet", "Bagaj küçük (361L)", "Sportif sürüş keyfi yok"],
    sentimentType: "POSITIVE",
    tarih: "2024-05-20",
  },

  {
    id: "rev-005",
    kategoriSlug: "otomobil",
    marka: "Dacia",
    model: "Duster",
    kasaKod: "2.Nesil",
    yil: 2018,
    kullanici: "burakdemir55",
    puan: 3,
    baslik: "Duster 2: Fiyat/Performans Şampiyonu Ama Konfor Değil",
    icerik: "Piyasada bu fiyata başka hiçbir araç bu hacmi ve kaplama yüksekliğini vermiyor, bunu kabul etmek gerekiyor. Ama uzun karayolu seyahatlerinde yol sesi gerçekten bunaltıcı bir hal alıyor, 120 km/s üstünde kulak tıkacı önerilir. İç malzeme tasarımı fonksiyonel ama görseli ucuz.",
    olumlu: ["Fiyat/hacim oranı rakipsiz", "Sağlam kaporta", "4x4 seçeneği cazip fiyatta"],
    olumsuz: ["Yüksek hızda aşırı yol sesi", "Plastik ağırlıklı iç mekan", "Direksiyon geri bildirimi zayıf", "Uzun yolda konfor eksikliği"],
    sentimentType: "TIP",
    tarih: "2023-09-14",
  },

  {
    id: "rev-006",
    kategoriSlug: "otomobil",
    marka: "Ford",
    model: "Focus",
    kasaKod: "Mk3",
    yil: 2015,
    kullanici: "emreozturk42",
    puan: 2,
    baslik: "Focus Mk3 PowerShift Şanzımanı Bizi Bitirdi",
    icerik: "3 yıl içinde PowerShift şanzımanı iki kez tamire girdi, ikinci seferinde 22 bin TL ödedik. Sürüş dinamikleri gerçekten etkileyici, özellikle virajlarda, ama şanzıman güvenilirliği bu aracı tavsiye etmemi engelliyor. Yetkili servis tuzak gibi, her giriş fatura kesilmeden çıkılmıyor.",
    olumlu: ["Sürüş dinamizmi segmentin üstünde", "Kabin ergonomisi iyi", "Yakıt tüketimi yolda makul (6.2L)"],
    olumsuz: ["PowerShift şanzıman kronik arızası", "Yüksek bakım maliyeti", "Yedek parça bulma güçlüğü", "Yetkili servis tutarsızlığı"],
    sentimentType: "COMPLAINT",
    tarih: "2024-01-30",
  },

  {
    id: "rev-007",
    kategoriSlug: "otomobil",
    marka: "Honda",
    model: "Civic",
    kasaKod: "FC/10.Nesil",
    yil: 2018,
    kullanici: "dilekarslan",
    puan: 4,
    baslik: "Civic FC5: Sürüş Keyfi ve Güvenilirlik Bir Arada",
    icerik: "110 bin km'de motor ve şanzımanda hiçbir sorun yaşamadım, bu durumu Türkiye'deki araç sahipliği için gerçekten nadir bir lüks olarak görüyorum. 1.5 VTEC motoru karayolunda hem güçlü hem ekonomik, 6 litrenin altında tüketim görüyorum. Tek şikayetim C pileri sesi, bozuk yollarda biraz gıcırdıyor.",
    olumlu: ["Üstün motor güvenilirliği", "Sportif sürüş keyfi", "Karayolunda yakıt ekonomisi (5.8L/100km)", "Geniş kabin"],
    olumsuz: ["C pilesi gıcırtısı bozuk yolda", "Honda servis ağı kısıtlı şehirlerde", "Arka görüşü kısıtlı"],
    sentimentType: "POSITIVE",
    tarih: "2024-07-03",
  },

  {
    id: "rev-008",
    kategoriSlug: "otomobil",
    marka: "Opel",
    model: "Astra",
    kasaKod: "K",
    yil: 2017,
    kullanici: "cagripolat",
    puan: 3,
    baslik: "Astra K: Ergonomi Mükemmel, Yedek Parça Felaketi",
    icerik: "Dikkat çekici bir iç tasarıma sahip, sürücü odaklı ergonomisi segment içinde en iyi diyebilirim. Ama 2022'de Opel Türkiye yetkili servislerini kapatınca yedek parça bulmak gerçek bir soruna dönüştü. Filtre değişimi bile fabrika parçası yerine muadil kullanmak zorunda kalıyorsunuz.",
    olumlu: ["Sürücü odaklı ergonomi", "Sessiz kabin", "Görece yakıt ekonomisi"],
    olumsuz: ["Yetkili servis ağı dağıldı", "Yedek parça temin güçlüğü", "İkinci el değer kaybı hızlı", "Arka koltuk dar"],
    sentimentType: "TIP",
    tarih: "2023-12-22",
  },

  {
    id: "rev-009",
    kategoriSlug: "otomobil",
    marka: "Hyundai",
    model: "i20",
    kasaKod: "BC3",
    yil: 2022,
    kullanici: "fatmakocer",
    puan: 4,
    baslik: "i20 BC3 ile İlk Araç Deneyimim: Beklentilerin Üstünde",
    icerik: "İlk arabam olarak BC3 aldım, doğru seçim yapmışım. Türkiye yollarının bozuk bölümlerinde süspansiyon performansı tatmin edici, kazaya uğrayan arkadaşımın Clio'suna kıyasla gürültüyü çok daha iyi süzüyor. Şehir içinde park sensörleriyle manevralar kolay, 1.0 T-GDI motorun gücü yeterli.",
    olumlu: ["Güçlü bozuk yol süspansiyon filtresi", "Modern güvenlik paketi", "Uygun sigorta maliyeti", "Geniş koltuk konforu"],
    olumsuz: ["Plastik göğüs paneli hafif titreşiyor", "Gece görüş mesafesi LED beklentisi karşılamıyor", "Orta kolçak yok (baz versiyon)"],
    sentimentType: "POSITIVE",
    tarih: "2024-03-11",
  },

  {
    id: "rev-010",
    kategoriSlug: "otomobil",
    marka: "Skoda",
    model: "Octavia",
    kasaKod: "NX",
    yil: 2021,
    kullanici: "tanergunay",
    puan: 5,
    baslik: "Octavia NX: Volkswagen Kalitesini Uygun Fiyata Almak",
    icerik: "Golf ile aynı platformu paylaşıyor ama 70-80 bin TL daha ucuza alındığında fark edilir bir değer sunuyor. 75 bin km'de bakım maliyetleri VW yetkili servisine kıyasla daha makul. Tek dikkat edilmesi gereken nokta: DSG kullanıyorsanız servis aralıklarına kesinlikle uyun, yoksa kavrama sorunu kaçınılmaz.",
    olumlu: ["Golf platformunda VW kalitesi", "Daha uygun bakım maliyeti", "595L bagaj kapasitesi (segmentin en büyüğü)", "Güçlü 1.5 TSI motor"],
    olumsuz: ["DSG bakım ihmalinde yüksek arıza riski", "Multimedia sistemi yavaş tepki veriyor", "Alüminyum pedal seti kaygan ıslak ayakkabıyla"],
    sentimentType: "TIP",
    tarih: "2024-06-08",
  },

  {
    id: "rev-011",
    kategoriSlug: "otomobil",
    marka: "BMW",
    model: "3 Serisi",
    kasaKod: "G20",
    yil: 2020,
    kullanici: "selimkaya",
    puan: 3,
    baslik: "G20 320i: Harika Dinamikler, Kabuslu Bakım Faturası",
    icerik: "Sürüş keyfi gerçekten kategorisinin en iyisi, özellikle arka tekerlekten çekişin verdiği denge hissi farklı. Ama Türkiye'de BMW sahipliği servis faturalarıyla gerçek bir psikolojik savaşa dönüşüyor. 45 bin km'de ön balata ve disk seti 28 bin TL çıktı. İkinci el değeri görece iyi duruyor.",
    olumlu: ["Sürüş dinamikleri segmentin en iyisi", "Prestij faktörü", "İkinci el değer tutma oranı iyi"],
    olumsuz: ["Bakım maliyeti aşırı yüksek", "Türkiye yollarında süspansiyon arızaları", "Kasko + vergi yükü ağır", "Yakıt tüketimi şehir içi 12L/100km"],
    sentimentType: "TIP",
    tarih: "2023-10-17",
  },

  {
    id: "rev-012",
    kategoriSlug: "otomobil",
    marka: "Mercedes-Benz",
    model: "C Serisi",
    kasaKod: "W205",
    yil: 2016,
    kullanici: "nuraydemirci",
    puan: 3,
    baslik: "C180 W205: Prestij Pahalıya Patlar",
    icerik: "2016 C180 aldım, görünüm ve kabin kalitesi etkileyici. Ama 55 bin km'de aktarma organlarıyla ilgili bir uyarı geldi, 14 bin TL ödedik. Türkiye'de Mercedes sahipliği yedek parça fiyatları nedeniyle ciddi düşünülmeli, özellikle garantisi bitmiş araçlarda. LPG dönüşümü yaptırmak istedik, önerilmiyor.",
    olumlu: ["Üstün kabin kalitesi ve sessizlik", "Güçlü ikinci el değeri", "Konforlu uzun yol sürüşü"],
    olumsuz: ["Garantisi biten araçta yüksek bakım maliyeti", "LPG dönüşümüne uygun değil", "Ön süspansiyon bozuk yolda çabuk aşınıyor", "Yakıt maliyeti ağır"],
    sentimentType: "COMPLAINT",
    tarih: "2024-04-09",
  },

  {
    id: "rev-013",
    kategoriSlug: "otomobil",
    marka: "Renault",
    model: "Megane",
    kasaKod: "4.Nesil",
    yil: 2019,
    kullanici: "koraykurt",
    puan: 4,
    baslik: "Megane 4 EDC: Türkiye Karayollarında Güvenilir Orta Sınıf",
    icerik: "1.3 TCe EDC kombinasyonu karayolunda 5.5 litre gibi düşük bir tüketim sağlıyor, bunu başından beri takip ediyorum. 80 bin km'de servis maliyetleri makul seyretti. Bozuk şehir yollarında gürültü biraz artıyor ama karayolunda tam anlamıyla konforu var. Garanti kapsamında bir sorun yaşamadım.",
    olumlu: ["Düşük karayolu yakıt tüketimi (5.5L)", "EDC şanzıman pürüzsüzlüğü", "Geniş ön kabin", "Güvenli frenleme mesafesi"],
    olumsuz: ["Şehir içi yakıt tüketimi 9.5L/100km", "Kötü yolda gürültü artar", "Dokunmatik ekran tepkileri bazen geç"],
    sentimentType: "POSITIVE",
    tarih: "2024-09-01",
  },

  {
    id: "rev-014",
    kategoriSlug: "otomobil",
    marka: "Peugeot",
    model: "208",
    kasaKod: "2.Nesil",
    yil: 2020,
    kullanici: "ebrunarin",
    puan: 4,
    baslik: "Peugeot 208 Mk2: Tasarım Kazandı, Gösterge Alıştırdı",
    icerik: "İlk hafta i-Cockpit gösterge sistemini küçük buldum ama bir ay sonra o kadar alıştım ki artık başka bir gösterge garip geliyor. 1.2 PureTech motor şehir içinde 7.8 litre gibi iyi bir ortalama veriyor. Türkiye Peugeot servis ağı büyük şehirlerde güçlü, küçük şehirlerde çok seçenek yok.",
    olumlu: ["Çarpıcı dış ve iç tasarım", "Şehir içi yakıt ekonomisi", "Segmentin en iyi gösterge deneyimi", "Kompakt ama kullanışlı kabin"],
    olumsuz: ["Servis ağı küçük şehirlerde zayıf", "Alışma gerektiren i-Cockpit yüksekliği", "Arka koltuk baş mesafesi dar"],
    sentimentType: "POSITIVE",
    tarih: "2023-08-25",
  },

  {
    id: "rev-015",
    kategoriSlug: "otomobil",
    marka: "TOGG",
    model: "T10X",
    kasaKod: "1.Nesil",
    yil: 2024,
    kullanici: "ahmetcelik",
    puan: 3,
    baslik: "TOGG T10X: Yerli Gurur Ama Şarj Altyapısı Henüz Hazır Değil",
    icerik: "Araç olarak etkileyici bir başlangıç, özellikle yazılım arayüzü ve iç mekan kalitesi beklentilerimin üstünde. Ama İstanbul dışında uzun yolculuk planlarken şarj noktası bulmak gerçek bir strese dönüşüyor. Ankara-İzmir güzergahında 3 farklı noktada kuyruğa girdim. Batarya soğukta 30 km daha düşük menzil veriyor.",
    olumlu: ["Yerli yazılım ve OTA güncellemeler", "Kabin kalitesi segmentinin üstünde", "Türkiye destek ve servis altyapısı büyüyor"],
    olumsuz: ["Şarj altyapısı büyük şehir dışında yetersiz", "Soğuk havada menzil kayıpları belirgin", "İkinci el piyasası henüz oluşmadı", "Uzun yol planlaması stresli"],
    sentimentType: "TIP",
    tarih: "2024-11-15",
  },

  // ─── ARAZİ & SUV (5 adet) ────────────────────────────────────────────────

  {
    id: "rev-016",
    kategoriSlug: "arazi-suv",
    marka: "Dacia",
    model: "Duster",
    kasaKod: "1.Nesil",
    yil: 2014,
    kullanici: "muratyildiz",
    puan: 4,
    baslik: "Duster 1.Nesil: Köy Yollarının Vazgeçilmezi",
    icerik: "Karadeniz bölgesinde çiftlik yollarında kullandım, 4x4 sistemi gerçekten güvenilir. 130 bin km'de ana aksamda herhangi bir sorun çıkmadı, sadece normal bakım yaptım. Fiyatı düşük tutmak için kullanılan plastik döşeme malzemesi yorucu ama 4x4 bu fiyata başka yerde yok. LPG dönüşümüne uygun ve verimli.",
    olumlu: ["Güvenilir 4x4 sistemi", "Uygun LPG dönüşümü", "Sağlam alt yapı", "Düşük bakım maliyeti"],
    olumsuz: ["İç mekan plastik kalitesi zayıf", "Çeşitli titreşim sesleri zamanla artar", "Yakıt tüketimi 4x4 açıkken yüksek"],
    sentimentType: "POSITIVE",
    tarih: "2023-07-19",
  },

  {
    id: "rev-017",
    kategoriSlug: "arazi-suv",
    marka: "Toyota",
    model: "RAV4",
    kasaKod: "XA50",
    yil: 2020,
    kullanici: "sinemakaya",
    puan: 5,
    baslik: "RAV4 Hybrid XA50: Aile SUV'unun Mükemmeli",
    icerik: "Hibrit sistemi şehir içinde gerçekten çarpıcı bir yakıt ekonomisi sağlıyor, İstanbul içinde 6.8 litre gibi değerler görüyorum ki bu büyüklükteki bir SUV için harika. 60 bin km'de hiçbir arıza yaşamadım. Toyota'nın bu segmentteki hibrit teknolojisi artık olgunlaştı ve güven veriyor. Yolda iken aküyü kendisi şarj ettiği için günlük kullanımda dışarıdan şarj endişesi yok.",
    olumlu: ["Şehir içi yakıt ekonomisi (6.8L)", "Toyota güvenilirliği", "Geniş aile pratikliği", "AWD+hibrit kombinasyonu"],
    olumsuz: ["Yüksek liste fiyatı", "Bagaj kapasitesi segment ortalamasının altında", "Sportif sürüş beklentisi karşılanamaz"],
    sentimentType: "POSITIVE",
    tarih: "2024-06-30",
  },

  {
    id: "rev-018",
    kategoriSlug: "arazi-suv",
    marka: "Hyundai",
    model: "Tucson",
    kasaKod: "TL",
    yil: 2017,
    kullanici: "ferhatpolat",
    puan: 3,
    baslik: "Tucson TL: Türkiye İkinci El Piyasasında İyi Konum Ama Yakıt Yorucu",
    icerik: "1.6 T-GDI benzinli versiyonuyla aldım ama şehir içi yakıt tüketimi beklentilerimi aşıyor, 12 litrenin altına indiremedim. 90 bin km'de turbo sistemi bakıma girdi, 9 bin TL tuttu. İkinci el piyasasında Tucson TL'nin değer kaybı yavaş, satmak istesem fiyatımı koruyacak.",
    olumlu: ["İkinci el değer tutma oranı yüksek", "Kabin konforu uzun yolda iyi", "Güvenlik sistemleri güçlü"],
    olumsuz: ["Şehir içi yakıt tüketimi yüksek (12L+)", "Turbo bakım maliyeti beklenenden yüksek", "Multimedia sistemi güncel değil", "Arka görüş kamerası gece kalitesi zayıf"],
    sentimentType: "TIP",
    tarih: "2024-02-28",
  },

  {
    id: "rev-019",
    kategoriSlug: "arazi-suv",
    marka: "Volkswagen",
    model: "Tiguan",
    kasaKod: "AD1",
    yil: 2018,
    kullanici: "ozlemdogan",
    puan: 4,
    baslik: "Tiguan AD1: Prim Ödemeye Değer Bir SUV",
    icerik: "Segment içindeki en pahalılardan biri ama hakikaten fark hissettiriyor. DSG şanzıman bu ağır araçta bile pürüzsüz çalışıyor ve 4Motion sistemi kış lastikleriyle birlikte Anadolu dağ yollarında güven veriyor. 85 bin km'de en ciddi masraf DSG yağ değişimi oldu, 4 bin TL.",
    olumlu: ["4Motion AWD sistemi güvenilir", "DSG pürüzsüz çalışma", "İç mekan kalitesi ve ses yalıtımı", "Güçlü ve düşük tüketimli 2.0 TDI"],
    olumsuz: ["Yüksek fiyat ve bakım maliyeti", "Benzinli versiyonlar DSG sorununa yatkın", "Park sensörü bazen hatalı uyarı veriyor"],
    sentimentType: "POSITIVE",
    tarih: "2024-08-07",
  },

  {
    id: "rev-020",
    kategoriSlug: "arazi-suv",
    marka: "Jeep",
    model: "Renegade",
    kasaKod: "BU",
    yil: 2016,
    kullanici: "berkaykurt",
    puan: 2,
    baslik: "Renegade: Tasarım Güzel, Güvenilirlik Berbat",
    icerik: "İtalya-Amerika ortak üretiminin en kötü yanları bir araya gelmiş gibi hissettiriyor. 55 bin km'de şanzıman tamiri 25 bin TL tuttu ve bu beklenen bir maliyet değildi. Bozuk Türkiye yollarında kaporta bağlantı parçaları gevşiyor, her altı ayda bir denetim gerekiyor. Görsel tasarım gerçekten farklı ama pratiklikte çok geride.",
    olumlu: ["Özgün ve dikkat çekici tasarım", "Geniş kabin görece beden için", "Off-road modu mevcut"],
    olumsuz: ["Şanzıman güvenilirliği ciddi sorun", "Bozuk yolda kaporta titremesi", "Yüksek bakım maliyeti", "Fiat/Jeep servis ağı tutarsız"],
    sentimentType: "COMPLAINT",
    tarih: "2023-11-30",
  },

  // ─── MOTOSİKLET (3 adet) ─────────────────────────────────────────────────

  {
    id: "rev-021",
    kategoriSlug: "motosiklet",
    marka: "Honda",
    model: "CB500F",
    kasaKod: "2.Nesil",
    yil: 2020,
    kullanici: "cemildogan",
    puan: 4,
    baslik: "CB500F: Yeni Sürücüler İçin Mükemmel Başlangıç",
    icerik: "Motosiklet lisansımı yeni aldığımda doğrudan bu modele geçtim ve hiç pişman olmadım. 471cc paralel ikili motor ne fazla ne az güç veriyor, sınırlarınızı tanımak için ideal. Türkiye'de Honda servis ağı güçlü, bakım maliyetleri büyük kapasitelere kıyasla makul. Yakıt tüketimi şehirde 4.2 litre gibi mükemmel.",
    olumlu: ["Yeni sürücü dostu güç eğrisi", "Güçlü Honda servis ağı", "Düşük yakıt tüketimi (4.2L/100km)", "Uzun servis aralıkları"],
    olumsuz: ["250cc'den gelenler için düşük hissedebilir", "Rüzgar koruması sıfır (yarı yarıya fairing yok)", "Üst viteslerde motor sesi artar"],
    sentimentType: "POSITIVE",
    tarih: "2024-04-22",
  },

  {
    id: "rev-022",
    kategoriSlug: "motosiklet",
    marka: "Yamaha",
    model: "MT-07",
    kasaKod: "2.Nesil",
    yil: 2019,
    kullanici: "orhanyalcin",
    puan: 4,
    baslik: "MT-07: Şehir ve Otoban için Dengeli Güç",
    icerik: "CP2 motoru Türkiye şehir trafiğinde rahat idare edilebilir bir karakter sergiliyor, ama otobanın açık kısımlarında da tatmin edici ivme veriyor. 35 bin km'de yalnızca zincir-dişli ve balata değiştirdim, motor bütünüyle sağlam. ABS sistemi slalom yapan bir araçla karşılaştığımda hayatımı kurtardı.",
    olumlu: ["Geniş kullanıcı yelpazesine hitap eden güç karakteri", "ABS sistemi güvenilir", "Düşük bakım maliyeti", "Hafif ağırlık (689cc için 184kg)"],
    olumsuz: ["Rüzgar koruması yok (yüksek hızda yorucu)", "İlk frenler biraz sert tutuyor", "Koltuk uzun yolda rahatsızlaştırıyor"],
    sentimentType: "POSITIVE",
    tarih: "2024-07-18",
  },

  {
    id: "rev-023",
    kategoriSlug: "motosiklet",
    marka: "Kawasaki",
    model: "Z900",
    kasaKod: "1.Nesil",
    yil: 2018,
    kullanici: "serkanakay",
    puan: 3,
    baslik: "Z900: Harika Motor Ama Türkiye Yolları Yakıyor",
    icerik: "Motor olarak muazzam, 125 beygir gücünü bu kadar doğal ve pürüzsüz aktaran başka bir inline-4 bilmiyorum. Ama Türkiye'nin çukurlu yollarında ön süspansiyon ayarı ciddi sorun çıkardı, 30 bin km'de kartuş değişimi gerekti ve 8.500 TL tuttu. Kasko maliyeti bu segmentte hayal kırıklığı yaratıyor.",
    olumlu: ["Etkileyici motor karakteri (125 HP)", "Sert görsel tasarım", "Fren performansı mükemmel"],
    olumsuz: ["Ön süspansiyon Türkiye yollarına dayanıksız", "Yüksek kasko maliyeti", "Yakıt tüketimi agresif sürüşte 7.5L/100km", "Uzun mesafe konforu zayıf"],
    sentimentType: "TIP",
    tarih: "2023-06-14",
  },

  // ─── TİCARİ (2 adet) ──────────────────────────────────────────────────────

  {
    id: "rev-024",
    kategoriSlug: "ticari",
    marka: "Ford",
    model: "Transit",
    kasaKod: "Mk8",
    yil: 2019,
    kullanici: "volkanturan",
    puan: 4,
    baslik: "Transit Mk8: Türkiye Lojistik Sektörünün Omurgası",
    icerik: "Nakliye işindeyim, 3 adet Transit kullanıyorum ve birinin 180 bin km'ye ulaştığında motor hâlâ sağlam. Yakıt verimliliği bu tonaj için gerçekten etkileyici, 2.0 EcoBlue motor 100 km'de 8.5 litreyle idare ediyor. Ford servis ağı Türkiye genelinde çok geniş, şehir dışında bile kapsamlı bakım yapılabiliyor.",
    olumlu: ["Yüksek km güvenilirliği", "Geniş Ford servis ağı", "İyi yakıt ekonomisi (8.5L/100km yüklü)", "Geniş yük kapasitesi"],
    olumsuz: ["İç mekan konfor minimum seviyede", "Çekici kullanırken motor ısınması", "Navigasyon sistemi basit"],
    sentimentType: "POSITIVE",
    tarih: "2024-10-03",
  },

  {
    id: "rev-025",
    kategoriSlug: "ticari",
    marka: "Mercedes-Benz",
    model: "Sprinter",
    kasaKod: "W907",
    yil: 2021,
    kullanici: "halilyilmaz",
    puan: 3,
    baslik: "Sprinter W907: Prestijli Ama Servis Maliyeti Ağır",
    icerik: "Amortisör ve aks sorunları 60 bin km'de belirdi, Türkiye yollarının ağır koşulları bunu hızlandırıyor. Yük kapasitesi ve sürüş konforu segmentin en iyisi ama 2 yıllık garantide iki ciddi tamir ödedik. Mercedes ticari araç garantisi beklentileri karşılamıyor, küçük şikayetler dahi tartışmaya dönüşüyor yetkili serviste.",
    olumlu: ["Yük kapasitesi ve organizasyon", "Sürücü konforu uzun mesafede iyi", "Güçlü ve ekonomik dizel motor"],
    olumsuz: ["Bozuk yolda süspansiyon ömrü kısa", "Yetkili servis tutumu güçleştiriyor", "Parça fiyatları çok yüksek", "Garanti kapsamı uygulamada kısıtlı"],
    sentimentType: "COMPLAINT",
    tarih: "2024-01-12",
  },

  // Test yorumu — Fiat Egea 2021
  {
    id: "rev-026",
    kategoriSlug: "otomobil",
    marka: "Fiat",
    model: "Egea",
    kasaKod: "356",
    yil: 2021,
    kullanici: "Ahmet",
    puan: 4,
    baslik: "3 Yılda Başımdan Geçenler",
    icerik: "2021 Egea aldım, ilk yıl harika geçti. İkinci yılda şanzıman titremesi başladı, servise götürdüm yazılım güncellemesi yaptılar geçti. Yakıt tüketimi şehirde 8-9L civarı, benim için kabul edilebilir. Kabin gürültüsü biraz fazla ama fiyatına göre mantıklı bir araç.",
    olumlu: ["Fiyat/performans", "Servis ağı", "Bagaj hacmi"],
    olumsuz: ["Kabin gürültüsü", "Şanzıman titremesi"],
    sentimentType: "POSITIVE",
    tarih: "2025-04-20",
  },
];
