export const vehicleImages: Record<string, string> = {
  // Otomobil - BMW
  "BMW_1 Serisi_E87": "",
  "BMW_1 Serisi_F20": "",
  "BMW_1 Serisi_F40": "https://commons.wikimedia.org/wiki/Special:FilePath/2019_BMW_118i_M_Sport_(F40)_front_8.7.19.jpg",
  "BMW_2 Serisi_F22": "",
  "BMW_2 Serisi_G42": "",
  "BMW_3 Serisi_E36": "",
  "BMW_3 Serisi_E46": "https://commons.wikimedia.org/wiki/Special:FilePath/BMW_E46_320d_Limousine_–_Frontansicht,_13._März_2011,_Velbert.jpg",
  "BMW_3 Serisi_E90": "https://commons.wikimedia.org/wiki/Special:FilePath/BMW_3er_(E90)_Facelift_20090720_front.JPG",
  "BMW_3 Serisi_F30": "https://commons.wikimedia.org/wiki/Special:FilePath/BMW_320i_(F30)_front.JPG",
  "BMW_3 Serisi_G20": "https://commons.wikimedia.org/wiki/Special:FilePath/BMW_G20_(2022)_IMG_7316_(2).jpg",
  "BMW_4 Serisi_F32": "",
  "BMW_4 Serisi_G22": "",
  "BMW_5 Serisi_E39": "",
  "BMW_5 Serisi_E60": "",
  "BMW_5 Serisi_F10": "",
  "BMW_5 Serisi_G30": "https://commons.wikimedia.org/wiki/Special:FilePath/2018_BMW_520d_SE_Saloon_(G30)_front_8.4.18.jpg",
  "BMW_5 Serisi_G60": "",
  "BMW_7 Serisi_E38": "",
  "BMW_7 Serisi_E65": "",
  "BMW_7 Serisi_F01": "",
  "BMW_7 Serisi_G11": "",
  "BMW_7 Serisi_G70": "",

  // Otomobil - Mercedes-Benz
  "Mercedes-Benz_A Serisi_W168": "",
  "Mercedes-Benz_A Serisi_W169": "",
  "Mercedes-Benz_A Serisi_W176": "",
  "Mercedes-Benz_A Serisi_W177": "https://commons.wikimedia.org/wiki/Special:FilePath/2019_Mercedes-Benz_A_200_SE_Automatic_1.3_Front.jpg",
  "Mercedes-Benz_B Serisi_W245": "",
  "Mercedes-Benz_B Serisi_W246": "",
  "Mercedes-Benz_B Serisi_W247": "",
  "Mercedes-Benz_C Serisi_W202": "",
  "Mercedes-Benz_C Serisi_W203": "",
  "Mercedes-Benz_C Serisi_W204": "https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes-Benz_W204_C200_01.JPG",
  "Mercedes-Benz_C Serisi_W205": "https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes-Benz_W205_IMG_3046.jpg",
  "Mercedes-Benz_C Serisi_W206": "https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes-Benz_W206_IMG_6380.jpg",
  "Mercedes-Benz_E Serisi_W210": "",
  "Mercedes-Benz_E Serisi_W211": "",
  "Mercedes-Benz_E Serisi_W212": "",
  "Mercedes-Benz_E Serisi_W213": "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Mercedes-Benz_E_220d_SE_(W213)_automatic_2.0_Front.jpg",
  "Mercedes-Benz_E Serisi_W214": "",
  "Mercedes-Benz_S Serisi_W140": "",
  "Mercedes-Benz_S Serisi_W220": "",
  "Mercedes-Benz_S Serisi_W221": "",
  "Mercedes-Benz_S Serisi_W222": "",
  "Mercedes-Benz_S Serisi_W223": "",

  // Otomobil - Audi
  "Audi_A3_8L": "",
  "Audi_A3_8P": "",
  "Audi_A3_8V": "",
  "Audi_A3_8Y": "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Audi_A3_S_Line_35_TFSI_S_Tronic_front_8.7.21.jpg",
  "Audi_A4_B5": "",
  "Audi_A4_B6": "",
  "Audi_A4_B7": "",
  "Audi_A4_B8": "",
  "Audi_A4_B9": "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Audi_A4_S_Line_35_TDI_Quattro_S-Tronic_front_8.7.21.jpg",
  "Audi_A4_B10": "",
  "Audi_A6_C5": "",
  "Audi_A6_C6": "",
  "Audi_A6_C7": "",
  "Audi_A6_C8": "",
  "Audi_A5_8T": "",
  "Audi_A5_F5": "",
  "Audi_A1_8X": "",
  "Audi_A1_GB": "",

  // Otomobil - Volkswagen
  "Volkswagen_Golf_Mk3": "",
  "Volkswagen_Golf_Mk4": "https://commons.wikimedia.org/wiki/Special:FilePath/VW_Golf_IV_1.6_(1997–2003)_front_MJ.JPG",
  "Volkswagen_Golf_Mk5": "https://commons.wikimedia.org/wiki/Special:FilePath/VW_Golf_V_wiki.JPG",
  "Volkswagen_Golf_Mk6": "",
  "Volkswagen_Golf_Mk7": "https://commons.wikimedia.org/wiki/Special:FilePath/2013_Volkswagen_Golf_1.4_TSI_BMT_Match_(9686562802).jpg",
  "Volkswagen_Golf_Mk8": "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Volkswagen_Golf_Style_1.5_Front.jpg",
  "Volkswagen_Passat_B5": "",
  "Volkswagen_Passat_B6": "",
  "Volkswagen_Passat_B7": "",
  "Volkswagen_Passat_B8": "https://commons.wikimedia.org/wiki/Special:FilePath/Volkswagen_Passat_B8_Limousine_2.0_TDI_DSG_Highline_–_Frontansicht,_19._April_2015,_Düsseldorf.jpg",
  "Volkswagen_Passat_B9": "",
  "Volkswagen_Polo_Mk3": "",
  "Volkswagen_Polo_Mk4": "",
  "Volkswagen_Polo_Mk5": "",
  "Volkswagen_Polo_Mk6": "https://commons.wikimedia.org/wiki/Special:FilePath/2018_Volkswagen_Polo_SEL_TSI_1.0_Front.jpg",
  "Volkswagen_Jetta_Mk4": "",
  "Volkswagen_Jetta_Mk5": "",
  "Volkswagen_Jetta_Mk6": "",
  "Volkswagen_Jetta_Mk7": "",
  "Volkswagen_Bora_1J": "",

  // Otomobil - Toyota
  "Toyota_Corolla_E100": "",
  "Toyota_Corolla_E110": "",
  "Toyota_Corolla_E120": "",
  "Toyota_Corolla_E140/E150": "",
  "Toyota_Corolla_E170": "",
  "Toyota_Corolla_E210": "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota_Corolla_Hybrid_(E210)_IMG_4338.jpg",
  "Toyota_Yaris_P10": "",
  "Toyota_Yaris_P90": "",
  "Toyota_Yaris_P130": "",
  "Toyota_Yaris_P210": "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Toyota_Yaris_Design_HEV_CVT_1.5_Front.jpg",
  "Toyota_Auris_E150": "",
  "Toyota_Auris_E180": "",
  "Toyota_Camry_XV40": "",
  "Toyota_Camry_XV50": "",
  "Toyota_Camry_XV70": "",

  // Otomobil - Renault
  "Renault_Megane_1.Nesil": "",
  "Renault_Megane_2.Nesil": "",
  "Renault_Megane_3.Nesil": "",
  "Renault_Megane_4.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/Renault_Megane_IV_–_Frontansicht,_27._September_2016,_Düsseldorf.jpg",
  "Renault_Clio_Mk1": "",
  "Renault_Clio_Mk2": "https://commons.wikimedia.org/wiki/Special:FilePath/Renault_Clio_II_Phase_I_Dreitürer_1.2.JPG",
  "Renault_Clio_Mk3": "https://commons.wikimedia.org/wiki/Special:FilePath/Renault_Clio_III_20090527_front.JPG",
  "Renault_Clio_Mk4": "",
  "Renault_Clio_Mk5": "https://commons.wikimedia.org/wiki/Special:FilePath/Renault_Clio_(V,_Facelift)_–_f_02092025.jpg",
  "Renault_Symbol_1.Nesil": "",
  "Renault_Symbol_2.Nesil": "",
  "Renault_Symbol_3.Nesil": "",
  "Renault_Fluence_L30": "",
  "Renault_Talisman_1.Nesil": "",
  "Renault_Laguna_X56": "",
  "Renault_Laguna_X74": "",
  "Renault_Laguna_X91": "",

  // Otomobil - Ford
  "Ford_Focus_Mk1": "",
  "Ford_Focus_Mk2": "https://commons.wikimedia.org/wiki/Special:FilePath/Ford_Focus_II_(Modellpflege,_seit_2008)_front_MJ.JPG",
  "Ford_Focus_Mk3": "https://commons.wikimedia.org/wiki/Special:FilePath/Ford_Focus_Mk3_Facelift_R.jpg",
  "Ford_Focus_Mk4": "https://commons.wikimedia.org/wiki/Special:FilePath/2019_Ford_Focus_ST-Line_X_1.5_EcoBlue_(facelift)_front_8.4.22.jpg",
  "Ford_Mondeo_Mk1": "",
  "Ford_Mondeo_Mk2": "",
  "Ford_Mondeo_Mk3": "",
  "Ford_Mondeo_Mk4": "",
  "Ford_Mondeo_Mk5": "",
  "Ford_Fiesta_Mk5": "",
  "Ford_Fiesta_Mk6": "",
  "Ford_Fiesta_Mk7": "https://commons.wikimedia.org/wiki/Special:FilePath/2018_Ford_Fiesta_Titanium_1.0_(facelift)_front_8.4.22.jpg",
  "Ford_Fusion_Mk1": "",

  // Otomobil - Fiat
  "Fiat_Egea_356": "https://commons.wikimedia.org/wiki/Special:FilePath/Fiat_Tipo_356_2016_front.jpg",
  "Fiat_Linea_323": "",
  "Fiat_Tipo_1.Nesil": "",
  "Fiat_Tipo_2.Nesil": "",
  "Fiat_Punto_188": "",
  "Fiat_Punto_199": "",
  "Fiat_Bravo_182": "",
  "Fiat_Bravo_198": "",
  "Fiat_Stilo_192": "",

  // Otomobil - Hyundai
  "Hyundai_i20_PB": "",
  "Hyundai_i20_GB": "",
  "Hyundai_i20_BC3": "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Hyundai_i20_Premium_T-GDi_front_8.7.21.jpg",
  "Hyundai_i30_FD": "",
  "Hyundai_i30_GD": "",
  "Hyundai_i30_PD": "",
  "Hyundai_Elantra_XD": "",
  "Hyundai_Elantra_HD": "",
  "Hyundai_Elantra_MD": "",
  "Hyundai_Elantra_AD": "",
  "Hyundai_Elantra_CN7": "",
  "Hyundai_Accent_LC": "",
  "Hyundai_Accent_MC": "",
  "Hyundai_Accent_RB": "",
  "Hyundai_Sonata_EF": "",
  "Hyundai_Sonata_NF": "",
  "Hyundai_Sonata_YF": "",
  "Hyundai_Sonata_LF": "",
  "Hyundai_Sonata_DN8": "",

  // Otomobil - Kia
  "Kia_Cerato_LD": "",
  "Kia_Cerato_TD": "",
  "Kia_Cerato_YD": "",
  "Kia_Cerato_BD": "",
  "Kia_Picanto_SA": "",
  "Kia_Picanto_TA": "",
  "Kia_Picanto_JA": "",
  "Kia_Rio_DC": "",
  "Kia_Rio_JB": "",
  "Kia_Rio_UB": "",
  "Kia_Rio_YB": "",
  "Kia_Stinger_CK": "",

  // Otomobil - Skoda
  "Skoda_Octavia_1U": "",
  "Skoda_Octavia_1Z": "",
  "Skoda_Octavia_5E": "",
  "Skoda_Octavia_NX": "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Skoda_Octavia_Style_TSI_front_8.7.21.jpg",
  "Skoda_Fabia_6Y": "",
  "Skoda_Fabia_5J": "",
  "Skoda_Fabia_NJ": "",
  "Skoda_Fabia_PJ": "",
  "Skoda_Superb_3U": "",
  "Skoda_Superb_3T": "",
  "Skoda_Superb_3V": "",
  "Skoda_Rapid_NH": "",

  // Otomobil - Dacia
  "Dacia_Logan_1.Nesil": "",
  "Dacia_Logan_2.Nesil": "",
  "Dacia_Logan_3.Nesil": "",
  "Dacia_Sandero_1.Nesil": "",
  "Dacia_Sandero_2.Nesil": "",
  "Dacia_Sandero_3.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Dacia_Sandero_Stepway_Comfort_SCe_65_front_8.7.21.jpg",
  "Dacia_Duster_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/Dacia_Duster_1.5_dCi_front_20100928.jpg",
  "Dacia_Duster_2.Nesil": "",
  "Dacia_Duster_3.Nesil": "",

  // Otomobil - Opel
  "Opel_Astra_F": "",
  "Opel_Astra_G": "https://commons.wikimedia.org/wiki/Special:FilePath/Opel_Astra_G_front.JPG",
  "Opel_Astra_H": "https://commons.wikimedia.org/wiki/Special:FilePath/Opel_Astra_H.JPG",
  "Opel_Astra_J": "https://commons.wikimedia.org/wiki/Special:FilePath/Opel_Astra_J.JPG",
  "Opel_Astra_K": "",
  "Opel_Astra_L": "",
  "Opel_Corsa_B": "",
  "Opel_Corsa_C": "",
  "Opel_Corsa_D": "",
  "Opel_Corsa_E": "",
  "Opel_Corsa_F": "",
  "Opel_Vectra_B": "",
  "Opel_Vectra_C": "",
  "Opel_Insignia_A": "",
  "Opel_Insignia_B": "",
  "Opel_Zafira_A": "",
  "Opel_Zafira_B": "",

  // Otomobil - Peugeot
  "Peugeot_206_2A/C": "",
  "Peugeot_207_WA/WC": "",
  "Peugeot_208_1.Nesil": "",
  "Peugeot_208_2.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/2020_Peugeot_208_Active_Premium_PureTech_front_8.4.22.jpg",
  "Peugeot_301_1.Nesil": "",
  "Peugeot_308_T7": "",
  "Peugeot_308_T9": "",
  "Peugeot_308_P51": "",
  "Peugeot_407_6D": "",
  "Peugeot_508_1.Nesil": "",
  "Peugeot_508_2.Nesil": "",

  // Otomobil - Citroën
  "Citroën_C3_1.Nesil": "",
  "Citroën_C3_2.Nesil": "",
  "Citroën_C3_3.Nesil": "",
  "Citroën_C4_B7": "",
  "Citroën_C4_B71": "",
  "Citroën_C4_2.Nesil": "",
  "Citroën_C5_X3": "",
  "Citroën_C5_RD/TD": "",
  "Citroën_Xsara Picasso_N68": "",

  // Otomobil - Honda
  "Honda_Civic_EK/6.Nesil": "",
  "Honda_Civic_EP/7.Nesil": "",
  "Honda_Civic_FD/8.Nesil": "",
  "Honda_Civic_FB/9.Nesil": "",
  "Honda_Civic_FC/10.Nesil": "",
  "Honda_Civic_FE/11.Nesil": "",
  "Honda_Accord_CG/6.Nesil": "",
  "Honda_Accord_CL/7.Nesil": "",
  "Honda_Accord_CP/8.Nesil": "",
  "Honda_Accord_CV/10.Nesil": "",
  "Honda_City_4.Nesil": "",
  "Honda_City_5.Nesil": "",
  "Honda_City_6.Nesil": "",
  "Honda_City_7.Nesil": "",
  "Honda_Jazz_GD": "",
  "Honda_Jazz_GE": "",
  "Honda_Jazz_GK": "",
  "Honda_Jazz_GR": "",

  // Otomobil - Nissan
  "Nissan_Micra_K11": "",
  "Nissan_Micra_K12": "",
  "Nissan_Micra_K13": "",
  "Nissan_Micra_K14": "",
  "Nissan_Almera_N15": "",
  "Nissan_Almera_N16": "",
  "Nissan_Primera_P10": "",
  "Nissan_Primera_P11": "",
  "Nissan_Primera_P12": "",
  "Nissan_Maxima_A33": "",

  // Otomobil - Mazda
  "Mazda_3_BK": "",
  "Mazda_3_BL": "",
  "Mazda_3_BM": "",
  "Mazda_3_BP": "",
  "Mazda_6_GG": "",
  "Mazda_6_GH": "",
  "Mazda_6_GJ": "",
  "Mazda_2_DE": "",
  "Mazda_2_DJ": "",

  // Otomobil - Mitsubishi
  "Mitsubishi_Lancer_CK/CL": "",
  "Mitsubishi_Lancer_CS": "",
  "Mitsubishi_Lancer_CY": "",
  "Mitsubishi_Carisma_DA": "",
  "Mitsubishi_Galant_EA": "",
  "Mitsubishi_Colt_Z30": "",

  // Otomobil - Volvo
  "Volvo_S40_V/N": "",
  "Volvo_S40_MS": "",
  "Volvo_S60_1.Nesil": "",
  "Volvo_S60_2.Nesil": "",
  "Volvo_S60_3.Nesil": "",
  "Volvo_S80_1.Nesil": "",
  "Volvo_S80_2.Nesil": "",
  "Volvo_V40_525/526": "",

  // Otomobil - SEAT
  "SEAT_Leon_1M": "",
  "SEAT_Leon_1P": "",
  "SEAT_Leon_5F": "",
  "SEAT_Leon_KL": "",
  "SEAT_Ibiza_Mk2": "",
  "SEAT_Ibiza_Mk3": "",
  "SEAT_Ibiza_Mk4": "",
  "SEAT_Ibiza_Mk5": "",
  "SEAT_Toledo_1M": "",
  "SEAT_Toledo_5P": "",
  "SEAT_Toledo_NH": "",
  "SEAT_Cordoba_6K": "",
  "SEAT_Cordoba_6L": "",

  // Otomobil - Subaru
  "Subaru_Impreza_GC/GF": "",
  "Subaru_Impreza_GD/GG": "",
  "Subaru_Impreza_GE/GH": "",
  "Subaru_Impreza_GP/GJ": "",
  "Subaru_Impreza_GT": "",
  "Subaru_Legacy_BD/BG": "",
  "Subaru_Legacy_BE/BH": "",
  "Subaru_Legacy_BL/BP": "",
  "Subaru_Legacy_BM/BR": "",
  "Subaru_Legacy_BS": "",

  // Otomobil - Suzuki
  "Suzuki_Swift_SF/AH": "",
  "Suzuki_Swift_RS": "",
  "Suzuki_Swift_FZ/NZ": "",
  "Suzuki_Swift_AZ": "",
  "Suzuki_Baleno_1.Nesil": "",
  "Suzuki_Baleno_2.Nesil": "",
  "Suzuki_Baleno_3.Nesil": "",
  "Suzuki_Liana_ER/RH": "",

  // Otomobil - TOGG
  "TOGG_T10X_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/TOGG_T10X.jpg",
  "TOGG_T10F_1.Nesil": "",

  // Otomobil - Alfa Romeo
  "Alfa Romeo_147_937": "",
  "Alfa Romeo_156_932": "",
  "Alfa Romeo_159_939": "",
  "Alfa Romeo_Giulia_952": "",
  "Alfa Romeo_Giulietta_940": "",

  // Otomobil - Mini
  "Mini_Cooper_R50/R53": "",
  "Mini_Cooper_R56": "",
  "Mini_Cooper_F56": "",
  "Mini_Cooper_J01": "",
  "Mini_Clubman_R55": "",
  "Mini_Clubman_F54": "",

  // Otomobil - Jeep
  "Jeep_Renegade_BU": "https://commons.wikimedia.org/wiki/Special:FilePath/Jeep_Renegade_01_--_Geneva_Motor_Show_--_2014-03-09.JPG",
  "Jeep_Compass_MK49": "",
  "Jeep_Compass_MP521": "",
  "Jeep_Cherokee_XJ": "",
  "Jeep_Cherokee_KJ": "",
  "Jeep_Cherokee_KK": "",
  "Jeep_Cherokee_KL": "",

  // Otomobil - Land Rover
  "Land Rover_Freelander_L314": "",
  "Land Rover_Freelander_L359": "",
  "Land Rover_Discovery Sport_L550": "",
  "Land Rover_Range Rover Evoque_L538": "",
  "Land Rover_Range Rover Evoque_L551": "",

  // Otomobil - Porsche
  "Porsche_911_996": "",
  "Porsche_911_997": "",
  "Porsche_911_991": "",
  "Porsche_911_992": "",
  "Porsche_Cayenne_9PA": "",
  "Porsche_Cayenne_92A": "",
  "Porsche_Cayenne_9YA": "",
  "Porsche_Panamera_970": "",
  "Porsche_Panamera_971": "",

  // Otomobil - Chevrolet
  "Chevrolet_Cruze_J300": "",
  "Chevrolet_Cruze_J400": "",
  "Chevrolet_Aveo_T250": "",
  "Chevrolet_Aveo_T300": "",
  "Chevrolet_Spark_M200": "",
  "Chevrolet_Spark_M300": "",
  "Chevrolet_Spark_M400": "",
  "Chevrolet_Captiva_C100": "",
  "Chevrolet_Captiva_C140": "",

  // Otomobil - Lexus
  "Lexus_IS_XE10": "",
  "Lexus_IS_XE20": "",
  "Lexus_IS_XE30": "",
  "Lexus_ES_XV40": "",
  "Lexus_ES_XV60": "",
  "Lexus_ES_XV70": "",
  "Lexus_CT_ZWA10": "",

  // Otomobil - Infiniti
  "Infiniti_Q50_V37": "",
  "Infiniti_G Serisi_V35": "",
  "Infiniti_G Serisi_V36": "",

  // Otomobil - Chery
  "Chery_Tiggo 8 Pro_1.Nesil": "",
  "Chery_Tiggo 7 Pro_1.Nesil": "",
  "Chery_Arrizo 5_1.Nesil": "",

  // Arazi & SUV - BMW
  "BMW_X1_E84": "",
  "BMW_X1_F48": "",
  "BMW_X1_U11": "",
  "BMW_X3_E83": "",
  "BMW_X3_F25": "",
  "BMW_X3_G01": "",
  "BMW_X5_E53": "",
  "BMW_X5_E70": "",
  "BMW_X5_F15": "",
  "BMW_X5_G05": "https://commons.wikimedia.org/wiki/Special:FilePath/BMW_G05_xDrive30d_–_Frontansicht,_7._Oktober_2018,_Düsseldorf.jpg",
  "BMW_X6_E71": "",
  "BMW_X6_F16": "",
  "BMW_X6_G06": "",

  // Arazi & SUV - Mercedes-Benz
  "Mercedes-Benz_GLA_X156": "",
  "Mercedes-Benz_GLA_H247": "",
  "Mercedes-Benz_GLC_X253": "",
  "Mercedes-Benz_GLC_X254": "",
  "Mercedes-Benz_GLE_W166": "",
  "Mercedes-Benz_GLE_V167": "",
  "Mercedes-Benz_GLK_X204": "",
  "Mercedes-Benz_ML_W163": "",
  "Mercedes-Benz_ML_W164": "",
  "Mercedes-Benz_ML_W166": "",

  // Arazi & SUV - Audi
  "Audi_Q3_8U": "",
  "Audi_Q3_F3": "",
  "Audi_Q5_8R": "",
  "Audi_Q5_FY": "",
  "Audi_Q7_4L": "",
  "Audi_Q7_4M": "",
  "Audi_Q2_GA": "",

  // Arazi & SUV - Jeep
  "Jeep_Grand Cherokee_ZJ": "",
  "Jeep_Grand Cherokee_WJ": "",
  "Jeep_Grand Cherokee_WK": "",
  "Jeep_Grand Cherokee_WK2": "",
  "Jeep_Grand Cherokee_WL": "",
  "Jeep_Wrangler_YJ": "",
  "Jeep_Wrangler_TJ": "",
  "Jeep_Wrangler_JK": "",
  "Jeep_Wrangler_JL": "",

  // Arazi & SUV - Land Rover
  "Land Rover_Range Rover_L322": "",
  "Land Rover_Range Rover_L405": "",
  "Land Rover_Range Rover_L460": "",
  "Land Rover_Range Rover Sport_L320": "",
  "Land Rover_Range Rover Sport_L494": "",
  "Land Rover_Range Rover Sport_L461": "",
  "Land Rover_Discovery_L319": "",
  "Land Rover_Discovery_L462": "",
  "Land Rover_Defender_L316": "",
  "Land Rover_Defender_L663": "",

  // Arazi & SUV - Porsche
  "Porsche_Macan_95B": "",
  "Porsche_Macan_J1": "",

  // Arazi & SUV - Volvo
  "Volvo_XC40_536": "",
  "Volvo_XC60_156": "",
  "Volvo_XC60_246": "",
  "Volvo_XC90_C/2.Nesil": "",
  "Volvo_XC90_256": "",

  // Arazi & SUV - Toyota
  "Toyota_RAV4_XA10": "",
  "Toyota_RAV4_XA20": "",
  "Toyota_RAV4_XA30": "",
  "Toyota_RAV4_XA40": "",
  "Toyota_RAV4_XA50": "https://commons.wikimedia.org/wiki/Special:FilePath/2021_Toyota_RAV4_engine_compartment.jpg",
  "Toyota_Land Cruiser_J80": "",
  "Toyota_Land Cruiser_J100": "",
  "Toyota_Land Cruiser_J200": "",
  "Toyota_Land Cruiser_J300": "",
  "Toyota_Land Cruiser Prado_J90": "",
  "Toyota_Land Cruiser Prado_J120": "",
  "Toyota_Land Cruiser Prado_J150": "",
  "Toyota_C-HR_AX10": "",
  "Toyota_C-HR_AX50": "",

  // Arazi & SUV - Nissan
  "Nissan_Qashqai_J10": "",
  "Nissan_Qashqai_J11": "",
  "Nissan_Qashqai_J12": "",
  "Nissan_X-Trail_T30": "",
  "Nissan_X-Trail_T31": "",
  "Nissan_X-Trail_T32": "",
  "Nissan_X-Trail_T33": "",
  "Nissan_Juke_F15": "",
  "Nissan_Juke_F16": "",
  "Nissan_Pathfinder_R51": "",
  "Nissan_Pathfinder_R52": "",
  "Nissan_Pathfinder_R53": "",

  // Arazi & SUV - Hyundai
  "Hyundai_Tucson_JM": "",
  "Hyundai_Tucson_LM": "",
  "Hyundai_Tucson_TL": "https://commons.wikimedia.org/wiki/Special:FilePath/2016_Hyundai_Tucson_(TL)_Active_2WD_wagon_(2017-07-15)_01.jpg",
  "Hyundai_Tucson_NX4": "",
  "Hyundai_Santa Fe_SM": "",
  "Hyundai_Santa Fe_CM": "",
  "Hyundai_Santa Fe_DM": "",
  "Hyundai_Santa Fe_TM": "",
  "Hyundai_Santa Fe_MX5": "",
  "Hyundai_ix35_EL": "",
  "Hyundai_Kona_OS": "",
  "Hyundai_Kona_SX2": "",

  // Arazi & SUV - Kia
  "Kia_Sportage_KM": "",
  "Kia_Sportage_SL": "",
  "Kia_Sportage_QL": "",
  "Kia_Sportage_NQ5": "",
  "Kia_Sorento_BL": "",
  "Kia_Sorento_XM": "",
  "Kia_Sorento_UM": "",
  "Kia_Sorento_MQ4": "",
  "Kia_Stonic_YB": "",

  // Arazi & SUV - Dacia
  "Dacia_Jogger_1.Nesil": "",

  // Arazi & SUV - Renault
  "Renault_Kadjar_1.Nesil": "",
  "Renault_Koleos_1.Nesil": "",
  "Renault_Koleos_2.Nesil": "",
  "Renault_Captur_J87": "",
  "Renault_Captur_J87ph2": "",

  // Arazi & SUV - Ford
  "Ford_Kuga_Mk1": "",
  "Ford_Kuga_Mk2": "",
  "Ford_Kuga_Mk3": "",
  "Ford_EcoSport_Mk2": "",
  "Ford_EcoSport_Mk3": "",
  "Ford_Puma_Mk1": "",

  // Arazi & SUV - Volkswagen
  "Volkswagen_Tiguan_5N": "",
  "Volkswagen_Tiguan_AD1": "https://commons.wikimedia.org/wiki/Special:FilePath/VW_Tiguan_2_2.0_TDI_(2016)_Frontansicht.jpg",
  "Volkswagen_Tiguan_BW2": "",
  "Volkswagen_T-Roc_A1": "",
  "Volkswagen_Touareg_7L": "",
  "Volkswagen_Touareg_7P": "",
  "Volkswagen_Touareg_CR": "",

  // Arazi & SUV - TOGG (SUV kategorisi)

  // Arazi & SUV - Opel
  "Opel_Mokka_J13": "",
  "Opel_Mokka_B": "",
  "Opel_Grandland_A18": "",
  "Opel_Antara_C100": "",

  // Arazi & SUV - Peugeot
  "Peugeot_2008_A94": "",
  "Peugeot_2008_P24": "",
  "Peugeot_3008_T84": "",
  "Peugeot_3008_P84": "",
  "Peugeot_3008_E3": "",
  "Peugeot_5008_T87": "",
  "Peugeot_5008_P87": "",

  // Arazi & SUV - Fiat
  "Fiat_Egea Cross_1.Nesil": "",
  "Fiat_500X_334": "",

  // Arazi & SUV - Mitsubishi
  "Mitsubishi_Outlander_CU": "",
  "Mitsubishi_Outlander_CW": "",
  "Mitsubishi_Outlander_GF/GG": "",
  "Mitsubishi_Outlander_4.Nesil": "",
  "Mitsubishi_ASX_GA": "",
  "Mitsubishi_ASX_2.Nesil": "",
  "Mitsubishi_Pajero_V20": "",
  "Mitsubishi_Pajero_V60/V70": "",
  "Mitsubishi_Pajero_V80/V90": "",

  // Motosiklet - Honda
  "Honda_CB500F_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/20250701_Honda_CB500F_in_Lucca.JPG",
  "Honda_CB500F_2.Nesil": "",
  "Honda_CB650R_1.Nesil": "",
  "Honda_CBR600RR_PC37": "",
  "Honda_CBR600RR_PC40": "",
  "Honda_CBR600RR_PC37-2": "",
  "Honda_CBR1000RR_SC57": "",
  "Honda_CBR1000RR_SC59": "",
  "Honda_CBR1000RR_SC77": "",
  "Honda_CBR1000RR_SC82": "",
  "Honda_NC750X_1.Nesil": "",
  "Honda_NC750X_2.Nesil": "",
  "Honda_Africa Twin_CRF1000L": "",
  "Honda_Africa Twin_CRF1100L": "",
  "Honda_PCX 125_JF28": "",
  "Honda_PCX 125_JF81": "",
  "Honda_PCX 125_JK05": "",

  // Motosiklet - Yamaha
  "Yamaha_MT-07_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/YAMAHA_MT-07.JPG",
  "Yamaha_MT-07_2.Nesil": "",
  "Yamaha_MT-07_3.Nesil": "",
  "Yamaha_MT-09_1.Nesil": "",
  "Yamaha_MT-09_2.Nesil": "",
  "Yamaha_MT-09_3.Nesil": "",
  "Yamaha_YZF-R1_4XV": "",
  "Yamaha_YZF-R1_5JJ": "",
  "Yamaha_YZF-R1_5VY": "",
  "Yamaha_YZF-R1_4C8": "",
  "Yamaha_YZF-R1_14B": "",
  "Yamaha_YZF-R1_RN32": "",
  "Yamaha_YZF-R6_5EB": "",
  "Yamaha_YZF-R6_5SL": "",
  "Yamaha_YZF-R6_2C0": "",
  "Yamaha_YZF-R6_RJ27": "",
  "Yamaha_Tracer 9_RN57": "",
  "Yamaha_TMAX_SJ01": "",
  "Yamaha_TMAX_SJ08": "",
  "Yamaha_TMAX_SJ12": "",
  "Yamaha_TMAX_SJ17": "",
  "Yamaha_TMAX_SJ20": "",

  // Motosiklet - Kawasaki
  "Kawasaki_Z650_1.Nesil": "",
  "Kawasaki_Z900_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/Kawasaki_Z900_FrontView.jpg",
  "Kawasaki_Z900_2.Nesil": "",
  "Kawasaki_Ninja 400_1.Nesil": "",
  "Kawasaki_Ninja ZX-6R_ZX636C": "",
  "Kawasaki_Ninja ZX-6R_ZX636D": "",
  "Kawasaki_Ninja ZX-6R_ZX636E": "",
  "Kawasaki_Ninja ZX-6R_ZX636G": "",
  "Kawasaki_Ninja ZX-10R_ZX1000C": "",
  "Kawasaki_Ninja ZX-10R_ZX1000D": "",
  "Kawasaki_Ninja ZX-10R_ZX1000E": "",
  "Kawasaki_Ninja ZX-10R_ZX1000J": "",
  "Kawasaki_Ninja ZX-10R_ZX1000S": "",
  "Kawasaki_Ninja ZX-10R_ZX1002E": "",
  "Kawasaki_Versys 650_1.Nesil": "",
  "Kawasaki_Versys 650_2.Nesil": "",

  // Motosiklet - Suzuki
  "Suzuki_GSX-R600_SRAD": "",
  "Suzuki_GSX-R600_K1-K3": "",
  "Suzuki_GSX-R600_K4-K5": "",
  "Suzuki_GSX-R600_K6-K7": "",
  "Suzuki_GSX-R600_K8-L0": "",
  "Suzuki_GSX-S750_1.Nesil": "",
  "Suzuki_V-Strom 650_1.Nesil": "",
  "Suzuki_V-Strom 650_2.Nesil": "",
  "Suzuki_V-Strom 650_3.Nesil": "",
  "Suzuki_Burgman 400_AN400": "",
  "Suzuki_Burgman 400_AN400A": "",
  "Suzuki_Burgman 400_AN400A2": "",

  // Motosiklet - BMW Motorrad
  "BMW Motorrad_R 1250 GS_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/2019_BMW_R_1250_GS_Adventure.jpg",
  "BMW Motorrad_R 1200 GS_R1200GS-1": "",
  "BMW Motorrad_R 1200 GS_R1200GS-2": "",
  "BMW Motorrad_S 1000 RR_1.Nesil": "",
  "BMW Motorrad_S 1000 RR_2.Nesil": "",
  "BMW Motorrad_F 850 GS_1.Nesil": "",
  "BMW Motorrad_G 310 R_1.Nesil": "",

  // Motosiklet - KTM
  "KTM_Duke 390_1.Nesil": "https://commons.wikimedia.org/wiki/Special:FilePath/KTM_Duke_390-01.jpg",
  "KTM_Duke 390_2.Nesil": "",
  "KTM_Duke 390_3.Nesil": "",
  "KTM_Duke 790_1.Nesil": "",
  "KTM_1290 Super Duke R_1.Nesil": "",
  "KTM_1290 Super Duke R_2.Nesil": "",
  "KTM_Adventure 890_1.Nesil": "",

  // Motosiklet - Ducati
  "Ducati_Monster_M600-M900": "",
  "Ducati_Monster_696/796/1100": "",
  "Ducati_Monster_821/1200": "",
  "Ducati_Monster_937": "",
  "Ducati_Panigale V4_1.Nesil": "",
  "Ducati_Panigale V4_2.Nesil": "",
  "Ducati_Multistrada_620/1000": "",
  "Ducati_Multistrada_1200": "",
  "Ducati_Multistrada_950/1260": "",
  "Ducati_Multistrada_V2/V4": "",
  "Ducati_Scrambler_1.Nesil": "",

  // Motosiklet - Triumph
  "Triumph_Street Triple_1.Nesil": "",
  "Triumph_Street Triple_2.Nesil": "",
  "Triumph_Street Triple_3.Nesil": "",
  "Triumph_Bonneville T120_1.Nesil": "",
  "Triumph_Tiger 900_1.Nesil": "",
  "Triumph_Speed Triple_T509": "",
  "Triumph_Speed Triple_1050": "",
  "Triumph_Speed Triple_1200": "",

  // Motosiklet - Royal Enfield
  "Royal Enfield_Classic 350_1.Nesil": "",
  "Royal Enfield_Classic 350_2.Nesil": "",
  "Royal Enfield_Meteor 350_1.Nesil": "",
  "Royal Enfield_Interceptor 650_1.Nesil": "",
  "Royal Enfield_Himalayan_1.Nesil": "",
  "Royal Enfield_Himalayan_2.Nesil": "",

  // Motosiklet - Harley-Davidson
  "Harley-Davidson_Sportster_XL883/1200": "",
  "Harley-Davidson_Sportster_S": "",
  "Harley-Davidson_Softail_FLSTC/FXST": "",
  "Harley-Davidson_Softail_FXST/FLST": "",
  "Harley-Davidson_Fat Boy_FLSTF": "",
  "Harley-Davidson_Fat Boy_FLFBS": "",
  "Harley-Davidson_Iron 883_XL883N": "",

  // Motosiklet - Aprilia
  "Aprilia_RS 660_1.Nesil": "",
  "Aprilia_Tuono V4_1.Nesil": "",
  "Aprilia_Tuono V4_2.Nesil": "",
  "Aprilia_Tuono V4_3.Nesil": "",
  "Aprilia_RSV4_1.Nesil": "",
  "Aprilia_RSV4_2.Nesil": "",
  "Aprilia_RSV4_3.Nesil": "",
  "Aprilia_SX 125_1.Nesil": "",

  // Motosiklet - Indian
  "Indian_Scout_1.Nesil": "",
  "Indian_Chief_1.Nesil": "",
  "Indian_Chief_2.Nesil": "",
  "Indian_FTR 1200_1.Nesil": "",

  // Motosiklet - Benelli
  "Benelli_TNT 135_1.Nesil": "",
  "Benelli_TNT 300_1.Nesil": "",
  "Benelli_TRK 502_1.Nesil": "",
  "Benelli_Leoncino 500_1.Nesil": "",

  // Minivan & Panelvan - Volkswagen
  "Volkswagen_Transporter_T4": "",
  "Volkswagen_Transporter_T5": "",
  "Volkswagen_Transporter_T6": "",
  "Volkswagen_Transporter_T6.1": "",
  "Volkswagen_Caddy_9K/9U": "",
  "Volkswagen_Caddy_2K": "",
  "Volkswagen_Caddy_SA": "",
  "Volkswagen_Caddy_SB": "",
  "Volkswagen_Multivan_T4": "",
  "Volkswagen_Multivan_T5": "",
  "Volkswagen_Multivan_T6/T6.1": "",
  "Volkswagen_Multivan_T7": "",
  "Volkswagen_Caravelle_T4": "",
  "Volkswagen_Caravelle_T5": "",
  "Volkswagen_Caravelle_T6/T6.1": "",

  // Minivan & Panelvan - Ford
  "Ford_Transit_Mk6": "",
  "Ford_Transit_Mk7": "",
  "Ford_Transit_Mk8": "",
  "Ford_Tourneo_Connect": "",
  "Ford_Tourneo_Courier": "",
  "Ford_Tourneo_Custom": "",
  "Ford_Transit Courier_1.Nesil": "",
  "Ford_Transit Courier_2.Nesil": "",
  "Ford_Transit Connect_Mk1": "",
  "Ford_Transit Connect_Mk2": "",
  "Ford_Transit Connect_Mk3": "",

  // Minivan & Panelvan - Mercedes-Benz
  "Mercedes-Benz_Vito_W638": "",
  "Mercedes-Benz_Vito_W639": "",
  "Mercedes-Benz_Vito_W447": "",
  "Mercedes-Benz_Sprinter_W901-905": "",
  "Mercedes-Benz_Sprinter_W906": "",
  "Mercedes-Benz_Sprinter_W907": "",
  "Mercedes-Benz_Viano_W639": "",
  "Mercedes-Benz_V Serisi_W447": "",

  // Minivan & Panelvan - Renault
  "Renault_Kangoo_KC": "",
  "Renault_Kangoo_KW": "",
  "Renault_Kangoo_FC": "",
  "Renault_Traffic / Trafic_T": "",
  "Renault_Traffic / Trafic_X83": "",
  "Renault_Traffic / Trafic_X82": "",
  "Renault_Master_T28-T35": "",
  "Renault_Master_X70": "",
  "Renault_Master_X62": "",
  "Renault_Master_X63": "",

  // Minivan & Panelvan - Peugeot
  "Peugeot_Partner_M49": "",
  "Peugeot_Partner_M59": "",
  "Peugeot_Partner_B9": "",
  "Peugeot_Partner_K9": "",
  "Peugeot_Boxer_230L": "",
  "Peugeot_Boxer_244": "",
  "Peugeot_Boxer_250": "",
  "Peugeot_Rifter_K9": "",
  "Peugeot_Traveller_V": "",

  // Minivan & Panelvan - Citroën
  "Citroën_Berlingo_M49": "",
  "Citroën_Berlingo_M59": "",
  "Citroën_Berlingo_B9": "",
  "Citroën_Berlingo_K9": "",
  "Citroën_Jumpy_U60": "",
  "Citroën_Jumpy_X": "",
  "Citroën_Jumpy_K0": "",
  "Citroën_Jumper_230L": "",
  "Citroën_Jumper_244": "",
  "Citroën_Jumper_250": "",
  "Citroën_SpaceTourer_1.Nesil": "",

  // Minivan & Panelvan - Fiat
  "Fiat_Doblo_119": "",
  "Fiat_Doblo_263": "",
  "Fiat_Doblo_BU7": "",
  "Fiat_Fiorino_146": "",
  "Fiat_Fiorino_225": "",
  "Fiat_Scudo_U60": "",
  "Fiat_Scudo_270": "",
  "Fiat_Scudo_K0": "",
  "Fiat_Ducato_230": "",
  "Fiat_Ducato_244": "",
  "Fiat_Ducato_250": "",

  // Minivan & Panelvan - Opel
  "Opel_Combo_B": "",
  "Opel_Combo_C": "",
  "Opel_Combo_D": "",
  "Opel_Combo_E": "",
  "Opel_Vivaro_A": "",
  "Opel_Vivaro_B": "",
  "Opel_Vivaro_C": "",
  "Opel_Movano_X70": "",
  "Opel_Movano_X62": "",

  // Minivan & Panelvan - Toyota
  "Toyota_ProAce_K0": "",
  "Toyota_HiAce_H100": "",
  "Toyota_HiAce_H200": "",
  "Toyota_HiAce_H300": "",

  // Minivan & Panelvan - Hyundai
  "Hyundai_H-1 / Starex_1.Nesil": "",
  "Hyundai_H-1 / Starex_2.Nesil": "",
  "Hyundai_H350_1.Nesil": "",

  // Minivan & Panelvan - Nissan
  "Nissan_NV200_M20": "",
  "Nissan_Primastar_X83": "",

  // Ticari - Ford
  "Ford_Transit (Kamyon)_Mk7": "",
  "Ford_Transit (Kamyon)_Mk8": "",
  "Ford_Cargo_0813/0815": "",
  "Ford_Cargo_1842/2533": "",
  "Ford_Trucks F-Max_1.Nesil": "",

  // Ticari - Volkswagen
  "Volkswagen_Crafter_2E": "",
  "Volkswagen_Crafter_SY/SZ": "",
  "Volkswagen_LT_40-55": "",

  // Ticari - Mercedes-Benz
  "Mercedes-Benz_Actros_MP1": "",
  "Mercedes-Benz_Actros_MP2": "",
  "Mercedes-Benz_Actros_MP3": "",
  "Mercedes-Benz_Actros_MP4": "",
  "Mercedes-Benz_Actros_MP5": "",
  "Mercedes-Benz_Sprinter (Ticari)_W906": "",
  "Mercedes-Benz_Sprinter (Ticari)_W907": "",
  "Mercedes-Benz_Atego_1.Nesil": "",
  "Mercedes-Benz_Atego_2.Nesil": "",
  "Mercedes-Benz_Axor_1.Nesil": "",

  // Ticari - Renault
  "Renault_Master (Ticari)_X70": "",
  "Renault_Master (Ticari)_X62": "",
  "Renault_Master (Ticari)_X63": "",
  "Renault_T Range_1.Nesil": "",
  "Renault_D Range_1.Nesil": "",

  // Ticari - Peugeot
  "Peugeot_Boxer (Ticari)_230": "",
  "Peugeot_Boxer (Ticari)_244": "",
  "Peugeot_Boxer (Ticari)_250": "",
  "Peugeot_Expert_U60": "",
  "Peugeot_Expert_G9": "",
  "Peugeot_Expert_K0": "",

  // Ticari - Citroën
  "Citroën_Jumper (Ticari)_230": "",
  "Citroën_Jumper (Ticari)_244": "",
  "Citroën_Jumper (Ticari)_250": "",
  "Citroën_Relay_250": "",

  // Ticari - Fiat
  "Fiat_Ducato (Ticari)_230": "",
  "Fiat_Ducato (Ticari)_244": "",
  "Fiat_Ducato (Ticari)_250": "",
  "Fiat_Doblo Cargo_119": "",
  "Fiat_Doblo Cargo_263": "",
  "Fiat_Doblo Cargo_BU7": "",

  // Ticari - Iveco
  "Iveco_Daily_2.Nesil": "",
  "Iveco_Daily_3.Nesil": "",
  "Iveco_Daily_4.Nesil": "",
  "Iveco_Daily_5.Nesil": "",
  "Iveco_Daily_6.Nesil": "",
  "Iveco_Stralis_1.Nesil": "",
  "Iveco_Stralis_Hi-Way": "",
  "Iveco_Stralis_S-Way": "",
  "Iveco_Trakker_1.Nesil": "",
  "Iveco_Trakker_2.Nesil": "",
  "Iveco_Eurocargo_Mk1": "",
  "Iveco_Eurocargo_Mk2": "",
  "Iveco_Eurocargo_Mk3": "",

  // Ticari - BMC
  "BMC_Pro_820": "",
  "BMC_Pro_Pro 22": "",
  "BMC_Fenix_1.Nesil": "",
  "BMC_Supercargo_1.Nesil": "",

  // Ticari - MAN
  "MAN_TGX_1.Nesil": "",
  "MAN_TGX_2.Nesil": "",
  "MAN_TGS_1.Nesil": "",
  "MAN_TGS_2.Nesil": "",
  "MAN_TGL_1.Nesil": "",

  // Ticari - Volvo Trucks
  "Volvo Trucks_FH_1.Nesil": "",
  "Volvo Trucks_FH_2.Nesil": "",
  "Volvo Trucks_FH_3.Nesil": "",
  "Volvo Trucks_FH_4.Nesil": "",
  "Volvo Trucks_FM_1.Nesil": "",
  "Volvo Trucks_FM_2.Nesil": "",
  "Volvo Trucks_FM_3.Nesil": "",
  "Volvo Trucks_FMX_1.Nesil": "",
  "Volvo Trucks_FMX_2.Nesil": "",

  // Ticari - Scania
  "Scania_R Serisi_R4": "",
  "Scania_R Serisi_R5": "",
  "Scania_R Serisi_Next Gen R": "",
  "Scania_G Serisi_Next Gen G": "",
  "Scania_S Serisi_Next Gen S": "",

  // Ticari - Isuzu
  "Isuzu_NKR_3.Nesil": "",
  "Isuzu_NKR_4.Nesil": "",
  "Isuzu_NPR_1.Nesil": "",
  "Isuzu_NPR_2.Nesil": "",
  "Isuzu_FVR_1.Nesil": "",
};

const categoryPlaceholders: Record<string, string> = {
  "otomobil": "/images/ph-otomobil.jpg",
  "arazi-suv": "/images/ph-suv.jpg",
  "motosiklet": "/images/ph-moto.jpg",
  "minivan-panelvan": "/images/ph-minivan.jpg",
  "ticari": "/images/ph-ticari.jpg",
};

export function getVehicleImage(
  marka: string,
  model: string,
  kasaKod: string,
  kategoriSlug: string = "otomobil"
): string {
  const key = `${marka}_${model}_${kasaKod}`;
  const url = vehicleImages[key];
  if (url) return url;
  return categoryPlaceholders[kategoriSlug] ?? "/images/ph-otomobil.jpg";
}
